const falcoLang = {
  keywords: [
    "rule",
    "macro",
    "list",
    "append",
    "enabled",
    "items",
    "desc",
    "output",
    "condition",
    "priority",
    "exceptions",
    "tags",
    "source",
    "required_engine_version",
    "true",
    "false",
  ],
  typeKeywords: [
    "contains",
    "icontains",
    "startswith",
    "endswith",
    "glob",
    "in",
    "intersects",
    "pmatch",
    "exists",
    "bcontains",
    "bstartswith",
  ],
  operators: ["and", "or", "not"],
};
