name: Cypress Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "ci.yml"
          repo: "falcosecurity/falco"
          name: falco-\d+\.\d+\.\d+-\d+\+[a-f0-9]+-wasm.tar.gz
          name_is_regexp: true
          
      - name: Extract artifact
        run: |
          tar -xvf falco-*-wasm.tar.gz/falco-*-wasm.tar.gz
          mv falco-*-wasm/usr/bin/falco.wasm ./public
          mv falco-*-wasm/usr/bin/falco.js ./src/Hooks/

      - name: Remove Unwanted Artifacts
        run: rm -rf falco-*-wasm.tar.gz falco-*-wasm

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:5173
          start: npx vite --host
